---
title: <span style="color:#034a94"> **Inferencia sobre los parámetros**</span>
author: "Modelos Estadisticos para la toma de decisiones"
output: html_document
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
library(vembedr)

c1="#FF7F00"
c2="#=EB0C6"
c3="#034A94"
c4="#686868"

```

</br></br>


## <span style="color:#034a94">**Inferencias sobre el intercepto $\beta_0$**</span>

</br>

El intercepto $\beta_{0}$ corresponde al valor que puede tomar la variable $Y$ cuando el valor de $X=0$ y se puede visualizar como el corte de la recta de regresión al eje $y$ en el plano carteciano. 
  
</br>

### <span style="color:#034a94">**Intervalos de confianza**</span>

</br>

Se puede demostrar que bajo los supuestos del modelo de regresión, se cumple que:

$$
{T} = {\frac{\widehat\beta_0 - \beta_0}{\sqrt{\frac{\widehat{\sigma}^2\sum^n_{i=1} x^2_i}{nS_{xx}}}} \sim t_{n - 2}}
$$
  
con ${t_{n-2}}$ la variable aleatoria ${t}$-Student con ${n-2}$ grados de libertad.


Por tanto un intervalo de confianza del ${(1-\alpha)\%}$ para ${\beta_0}$ para el intercepto está dado por:

$$
{\widehat\beta_0 \pm t_{\alpha/2, n-2}\times \sqrt{\frac{\widehat{\sigma}^2\sum^n_{i=1} x^2_i}{nS_{xx}}}}
$$


donde ${t_{\alpha/2, n - 2}}$ es el percentil ${1 - \alpha/2}$ de la distribución ${t}$-Student con ${n - 2}$ grados de libertad.

</br></br>

### <span style="color:#034a94">**Prueba de Hipótesis sobre la significancia del intercepto**</span>

</br>

Para probar si ${\beta_0}$ es significativamente distinto de cero se realiza la siguiente prueba de hipótesis :
   
</br>

|      hipótesis                |     estadístico de prueba              |
|:-----------------------------:|:--------------------------------------:|
|$H_0: \beta_0 = 0 \hspace{1cm}H_1: \beta_0 \neq 0$ |  ${T}={\dfrac{\widehat\beta_0-0}{\sigma_{\widehat{\beta}_{0}}} \sim t_{n-2}}$|
|                               |                                        |


El estadístico de prueba es la ecuación  y el valor observado de éste (${T_0}$) se halla reemplazando ${\beta_0}$ por 0. Se rechaza ${H_0}$ si ${|T_0| > t_{\alpha/2, n - 2}}$.

</br></br>

## <span style="color:#034a94">**Inferencias sobre la pendiente $\beta_1$**</span>

</br>

La pendiente $\beta_{1}$ permite determinar la razón de cambio de la variable $Y$ cuando ocurren cambios en $X$, que en ocaciones es el cetro del problema de al estimar un modelo de regresión. Si este valor es igual a cero estadísticamente significa que no existe relación estadística entre las variables y por tanto no tiene sentido la construcción de un modelo que las vincule.


</br></br>

### <span style="color:#034a94">**Intervalos de confianza**</span>

</br>

Se puede demostrar que bajo los supuestos del modelo de regresión, se cumple que:

$$
{T}={\frac{\widehat\beta_1-\beta_1}{\sqrt{\frac{\widehat{\sigma}^2}{S_{xx}}}} \sim t_{n-2}}
$$

  
   Por tanto un intervalo de confianza del ${(1-\alpha)\%}$ para ${\beta_1}$ es:
$$
{\widehat\beta_1 \pm t_{\alpha/2,n-2}\times \sqrt{\frac{\widehat{\sigma}^2}{S_{xx}}}}
$$

</br></br>

### <span style="color:#034a94">**Prueba de Hipótesis sobre la significancia de la pendiente**</span>

</br>

Para probar si ${\beta_1}$ es significativamente distinto de cero: 

</br>

|      hipótesis                |     estadístico de prueba              |
|:-----------------------------:|:--------------------------------------:|
| $H_0: \beta_1 = 0 \hspace{1cm}H_1: \beta_1 \neq 0$ |  ${T}={\dfrac{\widehat\beta_1-0}{\sqrt{\frac{\widehat{\sigma}^2}{S_{xx}}}} \sim t_{n-2}}$                 |
|                               |                                        | 

</br>

El estadístico de prueba es la  ecuación  y el valor observado de éste (${T_0}$) se halla reemplazando ${\beta_1}$ por 0. Se rechaza ${H_0}$ si ${|T_0|>t_{\alpha/2,n-2}}$.


</br></br>

<span style="color:#FF7F00">**Nota:**</span>

</br>

Observe que si la pendiente es significativa, entonces el modelo de RLS entre la predictora y la respuesta, también lo es.

